# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/optimalisatie_route_peilbuizen',
                'doc_host': 'https://Jelle de Jong.github.io',
                'git_url': 'https://github.com/Jelle de Jong/optimalisatie_route_peilbuizen',
                'lib_path': 'optimalisatie_route_peilbuizen'},
  'syms': { 'optimalisatie_route_peilbuizen.core': { 'optimalisatie_route_peilbuizen.core.foo': ( 'core.html#foo',
                                                                                                  'optimalisatie_route_peilbuizen/core.py')}}}
